_format_version: "1.1"
_workspace: default
services:
- connect_timeout: 60000
  host: httpbin.org
  name: service1
  path: /anything
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
